# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: a12b20f304720011ce86afd4c307e605807d7d9d9067ffd67efe9223f6c7c6e84640b1448123736fe233bb276025ef0a7a79c43211c12be1f762ca7c6f2a5915

test:
  secret_key_base: 2a095d0ca1b7fbf2a529a5a69d81a8cc85102e2a2e82ccbf81b957159bcd320d7b3bdd771809ac40b9a46f9ea0138f832fb99f4320583c4352c70c388a5a6778

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
